apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "banking-backend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "banking-backend.fullname" . }}

  template:
    metadata:
      labels:
        app: {{ include "banking-backend.fullname" . }}

    spec:
      containers:
        - name: banking-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}


          env:
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}

            - name: DB_PORT
              value: {{ .Values.database.port | quote }}

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: database

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: password

            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 20