{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "banking-backend.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.kubernetes.io/hostname: {{ .Values.ingress.host | quote }}

spec:
  ingressClassName: alb

  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: {{ include "banking-backend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}