apiVersion: v1
kind: Service
metadata:
  name: {{ include "banking-backend.fullname" . }}
spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ include "banking-backend.fullname" . }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP