apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: banking-db-secret
  namespace: default

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: banking-db-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: banking/dev/database
        property: username

    - secretKey: password
      remoteRef:
        key: banking/dev/database
        property: password

    - secretKey: database
      remoteRef:
        key: banking/dev/database
        property: database