apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-backend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/venkatesh-thomm/banking-platform-devops.git
    targetRevision: dev
    path: helm/banking-backend
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true